stages:
- prebuild
- build
- test
- pkg
- prepare
- release
- deploy  # dummy stage to follow the template guidelines
- review
- dast
- staging
- canary
- production
- incremental rollout 10%
- incremental rollout 25%
- incremental rollout 50%
- incremental rollout 100%
- performance
- cleanup

variables:
  TEST_DISABLED: "true"

include:
- template: Auto-DevOps.gitlab-ci.yml

